apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ "keycloak_user" | b64enc }}
  password: {{ "postgres" | b64enc }}
