{{- if .Values.postgresCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.postgresCredentials.username | b64enc }}
  password: {{ .Values.postgresCredentials.password | b64enc }}
{{- end }}
