{{- $vault := .Values.vault }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-vault-secrets
type: Opaque
data:
  ## MASTER
  #KEYCLOAK_CONFIG_CLI_CLIENT_SECRET
  master_keycloak-config-cli-client-secret: {{ $vault.master.keycloakConfigCliClientSecret | b64enc }}

  {{- $products := $vault.products }}
  mia-platform_external-identity-provider-client-secret: {{ $products.externalIdpClientSecret | b64enc }}
  ### extensibility idp SSO
  mia-platform_mia-platform-identity-provider-client-secret: {{ $products.idpClientSecret | b64enc }}
  {{- $extensibility := $vault.extensibility }}
  mia-platform-extensibility_mia-platform-identity-provider-client-secret: {{ $extensibility.idpClientSecret | b64enc }}
