{{- $secrets := .Files.Get "../../.local/secrets.yaml" | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-vault-secrets
type: Opaque
data:
  ## MASTER
  #KEYCLOAK_CONFIG_CLI_CLIENT_SECRET
  master_keycloak-config-cli-client-secret: {{ "change_me" | b64enc }}
  mia-platform_external-identity-provider-client-secret: {{ $secrets.clientSecret | quote | b64enc }}
  ### extensibility idp SSO
  mia-platform_mia-platform-identity-provider-client-secret: {{ $secrets.clientSecret | quote | b64enc }}
  mia-platform-extensibility_mia-platform-identity-provider-client-secret: {{ $secrets.clientSecret | quote | b64enc }}
