#!/usr/bin/env bash
set -euo pipefail

# Assembles charts/keycloak/.local/secrets.yaml from the key material
# in the repo-root .local/ (generated by hacks/setup_keys.sh).

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_LOCAL="$(cd "$SCRIPT_DIR/../.." && pwd)/.local"
OUT="$SCRIPT_DIR/.local/secrets.yaml"

mkdir -p "$(dirname "$OUT")"

jq -n \
    --rawfile clientSecret "$ROOT_LOCAL/client-secret" \
    '{
        clientSecret: ($clientSecret | rtrimstr("\n"))
    }' | yq -P > "$OUT"

echo "✅ Wrote keycloak secrets into $OUT"
