#!/usr/bin/env bash

set -euo pipefail

###############################################################################
# redis.sh — Install a standalone Redis (TLS-enabled) on cluster
#
# Environment:
#   REDIS_NAMESPACE   redis namespace (default: redis)
#   REDIS_PASSWORD    redis password (default: redis)
#   REDIS_PORT        redis TLS port (default: 6379)
#   KUBECONFIG        location of kubectl config file
###############################################################################

###############################################################################
# Helpers
###############################################################################

readonly GREEN='\033[32m'
readonly YELLOW='\033[33m'
readonly BLUE='\033[34m'
readonly RED='\033[31m'
readonly RESET='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${RESET}  $1"
}

log_ok() {
    echo -e "${GREEN}[OK]${RESET}    $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${RESET}  $*"
}

log_error() {
    echo -e "${RED}[ERROR]${RESET} $*"
}

REDIS_NAMESPACE=${REDIS_NAMESPACE:=redis}
REDIS_PASSWORD=${REDIS_PASSWORD:=redis}
REDIS_PORT=${REDIS_PORT:=6379}

RELEASE_NAME=redis
FULLNAME="${RELEASE_NAME}-master"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_LOCAL="${SCRIPT_DIR}/../.local"
CA_CERT_FILE="${ROOT_LOCAL}/redis-ca.pem"

###############################################################################
# Preflight — check required binaries
###############################################################################

REQUIRED_BINS=(helm)
missing=()

for bin in "${REQUIRED_BINS[@]}"; do
    if ! command -v "${bin}" &> /dev/null; then
        missing+=("${bin}")
    fi
done

if [[ ${#missing[@]} -gt 0 ]]; then
    log_error "Missing required" \
        "binaries: ${missing[*]}"
    exit 1
fi

###############################################################################
# Install Redis
###############################################################################

log_info "Adding Bitnami Helm repo..."
helm repo add bitnami \
    https://charts.bitnami.com/bitnami/ \
    --force-update >/dev/null 2>&1
helm repo update bitnami >/dev/null 2>&1

log_info "Installing standalone Redis (TLS-enabled)..."
helm upgrade --install ${RELEASE_NAME} bitnami/redis \
    --namespace ${REDIS_NAMESPACE} --create-namespace \
    --set architecture=standalone \
    --set auth.password=${REDIS_PASSWORD} \
    --set tls.enabled=true \
    --set tls.authClients=false \
    --set tls.autoGenerated=true \
    --set master.containerPorts.redis=${REDIS_PORT} \
    --set master.persistence.enabled=false \
    --wait

log_info "Waiting for Redis..."
kubectl wait --namespace ${REDIS_NAMESPACE} \
    --for=condition=ready pod \
    --selector=app.kubernetes.io/instance=${RELEASE_NAME},app.kubernetes.io/component=master \
    --timeout=120s

log_ok "Redis is ready."

###############################################################################
# Export the auto-generated CA cert
#
# tls.autoGenerated=true makes the chart mint its own self-signed CA at
# install time and store it only in the "${RELEASE_NAME}-crt" secret — it is
# never written to disk. Extract ca.crt so consumers (e.g. Console's
# configurations.redis.tlsCACert) can trust it.
###############################################################################

mkdir -p "${ROOT_LOCAL}"

log_info "Exporting Redis CA cert to ${CA_CERT_FILE}..."
kubectl get secret "${FULLNAME%-master}-crt" \
    --namespace ${REDIS_NAMESPACE} \
    -o jsonpath='{.data.ca\.crt}' \
    | base64 -d > "${CA_CERT_FILE}"

log_ok "CA cert exported."

###############################################################################
# Connection details
###############################################################################

HOST="${FULLNAME}.${REDIS_NAMESPACE}.svc.cluster.local"

log_ok "Host: ${HOST}"
log_ok "Port: ${REDIS_PORT} (TLS)"
log_ok "Password: ${REDIS_PASSWORD}"
log_ok "CA cert: ${CA_CERT_FILE}"
