#!/usr/bin/env bash
set -euo pipefail

# Assembles charts/catalog/.local/secrets.yaml from the key material
# in the repo-root .local/ (generated by hacks/setup_keys.sh) plus
# externally-sourced config (Postgres, Kafka, SMTP), which can be overridden
# via environment variables.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_LOCAL="$(cd "$SCRIPT_DIR/../.." && pwd)/.local"
OUT="$SCRIPT_DIR/.local/secrets.yaml"

mkdir -p "$(dirname "$OUT")"

FILES_CREDENTIALS_JSON='{}'
FILES_CREDENTIALS_B64=$(printf '%s' "$FILES_CREDENTIALS_JSON" | base64 | tr -d '\n')
RSA_PRIVATE_KEY_PEM="$(cat "$ROOT_LOCAL/client-private.pem")"
RSA_PRIVATE_KEY_B64=$(printf '%s\n' "$RSA_PRIVATE_KEY_PEM" | base64 | tr -d '\n')
CLIENT_ID_SALT='fake-client-id-salt-value'
CLIENT_ID_SALT_B64=$(printf '%s' "$CLIENT_ID_SALT" | base64 | tr -d '\n')

GITHUB_API_KEY='fake-github-api-key'
AZURE_LLM_API_KEY='azure-llm-api-key'

SMTP_USERNAME='smtp-username'
SMTP_PASSWORD='smtp-password'

jq -n \
    --rawfile privateKey   "$ROOT_LOCAL/client-private.pem" \
    --rawfile tokenEncKey  "$ROOT_LOCAL/redis-token-enc.key" \
    --rawfile cookieSecret "$ROOT_LOCAL/cookie-secret.key" \
    --rawfile redisCaCert  "$ROOT_LOCAL/redis-ca.pem" \
    --arg mongodbUrl "mongodb://root:mongo@mongo-mongodb-0.mongo-mongodb-headless.mongo.svc.cluster.local:27017,mongo-mongodb-1.mongo-mongodb-headless.mongo.svc.cluster.local:27017,mongo-mongodb-2.mongo-mongodb-headless.mongo.svc.cluster.local:27017/console?replicaSet=rs0&authSource=admin" \
    --arg redisPassword "redis" \
    --arg filesCredentials "$FILES_CREDENTIALS_B64" \
    --arg rsaPrivateKeyBase64 "$RSA_PRIVATE_KEY_B64" \
    --arg rsaPrivateKeyId "fake-rsa-key-id-12345" \
    --arg clientIdSalt "$CLIENT_ID_SALT_B64" \
    --arg azureLlmApiKey "$AZURE_LLM_API_KEY" \
    --arg githubApiKey "$GITHUB_API_KEY" \
    --arg smtpUsername "$SMTP_USERNAME" \
    --arg smtpPassword "$SMTP_PASSWORD" \
    '{
        "mia-console": {
            configurations: {
                redis: {
                    password: $redisPassword,
                    tlsCACert: $redisCaCert
                },
                mailSender: {
                    smtp: {
                        username: $smtpUsername,
                        password: $smtpPassword
                    }
                },
                mongodbUrl: $mongodbUrl,
                filesCredentials: $filesCredentials,
                serviceAccountAuthProvider: {
                    rsaPrivateKeyBase64: $rsaPrivateKeyBase64,
                    rsaPrivateKeyId: $rsaPrivateKeyId,
                    clientIdSalt: $clientIdSalt
                },
                assistant: {
                    keys: {
                        azureLlmApiKey: $azureLlmApiKey,
                        github: $githubApiKey
                    },
                    embeddings: { apiKey: $azureLlmApiKey }
                },
                audit: {
                    envs: { mongodbUrl: $mongodbUrl },
                },
            },
            authtoolBff: {
                keys: {
                    privateKey: $privateKey,
                    cookieSecret: $cookieSecret,
                    redisTokenEncKey: $tokenEncKey
                }
            },
            extensibilityManagerService: {
                keys: { registrarPrivateKey: $privateKey }
            }
        }
    }' | yq -P > "$OUT"

echo "✅ Wrote catalog secrets into $OUT"
