
mia-console:
  imagePullSecrets:
    - name: nexus-gcloud

  configurations:
    consoleUrl: "https://console.mia-platform.test"
    cmsUrl: "https://cms-console.mia-platform.test"
    audit: {}

    keycloak:
      protocol: "https"
      host: "auth.mia-platform.test"
      realm: "mia-platform"
      extensibilityRealmName: "mia-platform-extensibility"
    enablePrometheusMetrics: false
    ####### uncomment these values only if you want to use gcp as a keyProvider
    ####### however you need an actual GCP infrastructure.
    # crudEncryption:
    #   keyVaultNamespace: 'console.credentials-encryption'
    #   kmsProvider: 'gcp'
    #   gcpConfig:
    #     email: 'kms-user@my-project.iam.gserviceaccount.com'
    #     projectId: 'my-project'
    #     location: 'europe'
    #     keyRing: 'my-project-keyring'
    #     keyName: 'my-project'
    #     privateKey: 'my-private-key'
    mailSender:
      senderAddress: "Mia-Platform (no-reply@mia-platform.eu)"
      notifier: "smtp"
      smtp:
        host: "email-smtp.eu-west-1.amazonaws.com"
        port: "587"
    redis:
      hosts:
        - ip: redis-master.redis.svc.cluster.local
          port: 6379
      username: default
      tls: true
    assistant:
      enabled: false
      llms: []
      embeddings: {}
