#!/usr/bin/env bash
set -euo pipefail

# Assembles charts/ai-foundry/.local/secrets.yaml from the key material
# in the repo-root .local/ (generated by hacks/setup_keys.sh) plus
# externally-sourced config (Postgres, Kafka, SMTP), which can be overridden
# via environment variables.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_LOCAL="$(cd "$SCRIPT_DIR/../.." && pwd)/.local"
OUT="$SCRIPT_DIR/.local/secrets.yaml"

mkdir -p "$(dirname "$OUT")"

jq -n \
    --rawfile privateKey   "$ROOT_LOCAL/client-private.pem" \
    --rawfile tokenEncKey  "$ROOT_LOCAL/redis-token-enc.key" \
    --rawfile cookieSecret "$ROOT_LOCAL/cookie-secret.key" \
    --arg pgConn         "${AI_FOUNDRY_PG_CONN:-postgresql://ai_foundry_user_user:postgres@postgres-postgresql.postgres.svc.cluster.local:5432/ai_foundry_user}" \
    --arg pgConnAdk      "${ADK_PG_CONN:-postgresql+asyncpg://adk_user:postgres@postgres-postgresql.postgres.svc.cluster.local:5432/adk}" \
    --arg kafkaBootstrap "${AI_FOUNDRY_KAFKA_BOOTSTRAP:-catalog-kafka-kafka-bootstrap.catalog.svc:9092}" \
    --arg smtpUsername   "${AI_FOUNDRY_SMTP_USERNAME:-}" \
    --arg smtpPassword   "${AI_FOUNDRY_SMTP_PASSWORD:-}" \
    '{
        "ai-foundry": {
            secrets: {
                accessControlKeys: {
                    privateKey: $privateKey
                },
                authtoolBffKeys: {
                    tokenEncKey:  ($tokenEncKey  | rtrimstr("\n")),
                    cookieSecret: ($cookieSecret | rtrimstr("\n")),
                    website:  { privateKey: $privateKey },
                    exchangeAuthz: { privateKey: $privateKey },
                    exchangeCatalog: { privateKey: $privateKey }
                },
                adkBeAppKeys: {
                    googleApplicationCredentials: "",
                    postgresConnectionString: $pgConnAdk
                }
            }
        }
    }' | yq -P > "$OUT"

echo "✅ Wrote AI Foundry secrets into $OUT"
