apiVersion: v2
name: mia-on-prem
description: Umbrella chart bundling Mia Platform Console stack for on-prem deployment
type: application
version: 15.0.0
appVersion: 15.0.0

dependencies:
  - name: keycloak-realm-management
    version: ~0.1
    repository: "https://nexus.mia-platform.eu/repository/helm-internal/"
