#!/usr/bin/env bash
set -euo pipefail

# Assembles charts/services/.local/secrets.yaml from the shared key material
# in the repo-root .local/ (generated by hacks/setup_keys.sh) plus
# externally-sourced config (Postgres), which can be overridden via
# environment variables.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_LOCAL="$(cd "$SCRIPT_DIR/../.." && pwd)/.local"
OUT="$SCRIPT_DIR/.local/secrets.yaml"

mkdir -p "$(dirname "$OUT")"

jq -n \
    --rawfile privateKey   "$ROOT_LOCAL/client-private.pem" \
    --rawfile tokenEncKey  "$ROOT_LOCAL/redis-token-enc.key" \
    --rawfile cookieSecret "$ROOT_LOCAL/cookie-secret.key" \
    --arg pgConnAuthz "${AUTHZ_PG_CONN:-postgresql://authz_user:postgres@postgres-postgresql.postgres.svc.cluster.local:5432/authz}" \
    --arg pgConnAdk   "${ADK_PG_CONN:-postgresql+asyncpg://adk_user:postgres@postgres-postgresql.postgres.svc.cluster.local:5432/adk}" \
    '{
        services: {
            secrets: {
                adkBeAppKeys: {
                    googleApplicationCredentials: "",
                    postgresConnectionString: $pgConnAdk
                },
                authtoolBffKeys: {
                    tokenEncKey:  ($tokenEncKey  | rtrimstr("\n")),
                    cookieSecret: ($cookieSecret | rtrimstr("\n")),
                    privateKey:   $privateKey
                },
                rbacManagementKeys: {
                    postgresConnectionString: $pgConnAuthz,
                    privateKey: $privateKey
                }
            }
        }
    }' | yq -P > "$OUT"

echo "✅ Wrote services secrets into $OUT"
