#!/usr/bin/env bash
set -euo pipefail

# Assembles charts/catalog/.local/secrets.yaml from the key material
# in the repo-root .local/ (generated by hacks/setup_keys.sh) plus
# externally-sourced config (Postgres, Kafka, SMTP), which can be overridden
# via environment variables.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_LOCAL="$(cd "$SCRIPT_DIR/../.." && pwd)/.local"
OUT="$SCRIPT_DIR/.local/secrets.yaml"

mkdir -p "$(dirname "$OUT")"

jq -n \
    --rawfile privateKey   "$ROOT_LOCAL/client-private.pem" \
    --rawfile tokenEncKey  "$ROOT_LOCAL/redis-token-enc.key" \
    --rawfile cookieSecret "$ROOT_LOCAL/cookie-secret.key" \
    --arg pgConn         "${CATALOG_PG_CONN:-postgresql://catalog_user:postgres@postgres-postgresql.postgres.svc.cluster.local:5432/catalog}" \
    --arg pgConnAdk      "${ADK_PG_CONN:-postgresql+asyncpg://adk_user:postgres@postgres-postgresql.postgres.svc.cluster.local:5432/adk}" \
    --arg kafkaBootstrap "${CATALOG_KAFKA_BOOTSTRAP:-catalog-kafka-kafka-bootstrap.catalog.svc:9092}" \
    --arg smtpUsername   "${CATALOG_SMTP_USERNAME:-}" \
    --arg smtpPassword   "${CATALOG_SMTP_PASSWORD:-}" \
    '{
        catalog: {
            secrets: {
                accessControlKeys: {
                    privateKey: $privateKey
                },
                authtoolBffKeys: {
                    tokenEncKey:  ($tokenEncKey  | rtrimstr("\n")),
                    cookieSecret: ($cookieSecret | rtrimstr("\n")),
                    website:  { privateKey: $privateKey },
                    exchange: { privateKey: $privateKey }
                },
                adkBeAppKeys: {
                    googleApplicationCredentials: "",
                    postgresConnectionString: $pgConnAdk
                },
                catalogEngineKeys: {
                    postgresConnectionString: $pgConn
                },
                itemsCompressorKeys: {
                    postgresConnectionString: $pgConn
                },
                kafkaKeys: {
                    bootstrapServers: $kafkaBootstrap
                },
                mailServiceKeys: {
                    smtpUsername: $smtpUsername,
                    smtpPassword: $smtpPassword
                }
            }
        }
    }' | yq -P > "$OUT"

echo "✅ Wrote catalog secrets into $OUT"
