{{- $secrets :=  .Files.Get "../../.local/secrets.yaml" | fromYaml }}
catalog:
  secrets:
    accessControlKeys:
      privateKey: {{ $secrets.privateKey }}
    authtoolBffKeys:
      tokenEncKey: {{ $secrets.tokenEncKey }}
      cookieSecret: {{ $secrets.cookieSecret }}
      website:
        privateKey: {{ $secrets.privateKey }}
      exchange:
        privateKey: {{ $secrets.privateKey }}
    adkBeAppKeys:
      googleApplicationCredentials: ""
      postgresConnectionString: postgresql+asyncpg://adk_user:postgres@postgres-postgresql.postgres.svc.cluster.local:5432/adk
    catalogEngineKeys:
      postgresConnectionString: postgresql://catalog_user:postgres@postgres-postgresql.postgres.svc.cluster.local:5432/catalog
    itemsCompressorKeys:
      postgresConnectionString: postgresql://catalog_user:postgres@postgres-postgresql.postgres.svc.cluster.local:5432/catalog
    kafkaKeys:
      bootstrapServers: catalog-kafka-kafka-bootstrap.catalog.svc:9092
    mailServiceKeys:
      smtpUsername: ""
      smtpPassword: ""
