# yaml-language-server: $schema=./values.schema.json
catalog:
  url: "https://catalog.mia-platform.test"

  authzUrl: "https://home.mia-platform.test"

  ingressRoute:
    enabled: true

  catalogKafkaContext:
    topics:
      input: "catalog-events.input"
      output: "catalog-events.output"
    connectionConfig:
      useBootstrapServers: true
      useSaslUsername: false
      useSaslPassword: false
      saslMechanism: PLAIN
      securityProtocol: PLAINTEXT

  authorizationServer:
    issuer: "https://auth.mia-platform.test/realms/mia-platform"

  telemetry:
    enabled: true
    otelExporterOtlpEndpoint: http://opentelemetry-collector.tracing-system.svc.cluster.local:4317
    otelExporterOtlpProtocol: grpc

  secrets:
    accessControlKeys:
      enabled: true
    adkBeAppKeys:
      enabled: true
    authtoolBffKeys:
      enabled: true
    catalogEngineKeys:
      enabled: true
    itemsCompressorKeys:
      enabled: true
    kafkaKeys:
      enabled: true
    mailServiceKeys:
      enabled: true

  apiGateway:
    extraVirtualHosts:
      - "*"

  accessControl:
    logLevel: debug

  adkBeApp:
    config:
      googleCloudProject: "operations-lab"
      googleCloudLocation: "europe-west1"
      googleGenaiUseVertexai: true
      otelExporterOtlpEndpoint: http://opentelemetry-collector.tracing-system.svc.cluster.local:4318
      otelExporterOtlpProtocol: http/protobuf

  doclingService:
    enabled: true

  itemsCompressor:
    config:
      kafkaConsumerConfig:
        group.id: cg.catalog.item-compressor-dev
        auto.offset.reset: earliest
        queued.max.messages.kbytes: "32840"
        queued.min.messages: "5000"
      kafkaProducerConfig:
        compression.type: snappy
      postgresConfig:
        cache:
          enabled: true
          tableName: "item_compressor_development_cache"
          schemaName: "items_compressor_development_schema"

  itemsConsumer:
    config:
      kafkaConfig:
        group.id: cg.catalog.items-consumer-dev

  mailService:
    config:
      host: "email-smtp.eu-west-1.amazonaws.com"

  swaggerAggregator:
    enabled: true
