{{- $secrets := .Files.Get "../../.local/secrets.yaml" | fromYaml }}
services:
  secrets:
    authtoolBffKeys:
      tokenEncKey: {{ $secrets.tokenEncKey }}
      cookieSecret: {{ $secrets.cookieSecret }}
      privateKey: {{ $secrets.privateKey }}
    rbacManagementKeys:
      postgresConnectionString: postgresql://authz_user:postgres@postgres-postgresql.postgres.svc.cluster.local:5432/authz
      privateKey: {{ $secrets.privateKey }}
